const axios = require('axios');

async function testRehabilitationPlanAPI() {
  try {
    console.log('Testing Rehabilitation Plan API...');
    
    // Login as clinician
    const loginResponse = await axios.post('http://localhost:5000/api/auth/login', {
      email: 'projectklouds24@gmail.com',
      password: 'password123'
    });
    
    const token = loginResponse.data.token;
    console.log('✅ Clinician login successful');
    
    // Get cases to find a case ID
    const casesResponse = await axios.get('http://localhost:5000/api/cases', {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      }
    });
    
    console.log('✅ Cases fetched successfully');
    console.log('Total cases:', casesResponse.data.cases?.length || 0);
    
    if (casesResponse.data.cases && casesResponse.data.cases.length > 0) {
      const caseData = casesResponse.data.cases[0];
      const caseId = caseData._id;
      const workerId = caseData.worker._id;
      
      console.log(`\n📋 Using case: ${caseData.caseNumber}`);
      console.log(`Worker: ${caseData.worker.firstName} ${caseData.worker.lastName}`);
      
      // Create a rehabilitation plan
      const planData = {
        case: caseId,
        worker: workerId,
        planName: "Today's Recovery Plan",
        planDescription: "Daily recovery exercises and activities for worker rehabilitation",
        exercises: [
          {
            name: "Neck Stretches",
            description: "Gentle neck stretching exercises",
            duration: 5,
            category: "stretching",
            difficulty: "easy",
            instructions: "Slowly tilt your head to each side and hold for 10 seconds"
          },
          {
            name: "Shoulder Rolls",
            description: "Shoulder mobility exercises",
            duration: 3,
            category: "stretching",
            difficulty: "easy",
            instructions: "Roll your shoulders forward and backward in circular motions"
          },
          {
            name: "Back Extensions",
            description: "Back strengthening exercises",
            duration: 8,
            category: "strengthening",
            difficulty: "medium",
            instructions: "Lie on your stomach and gently lift your chest off the ground"
          },
          {
            name: "Walking",
            description: "Light walking exercise",
            duration: 15,
            category: "cardio",
            difficulty: "easy",
            instructions: "Take a gentle walk at a comfortable pace"
          }
        ],
        settings: {
          autoGenerateDaily: true,
          reminderTime: "09:00",
          allowSkipping: true,
          maxConsecutiveSkips: 2,
          progressMilestoneDays: 5
        }
      };
      
      console.log('\n🏗️ Creating rehabilitation plan...');
      const planResponse = await axios.post('http://localhost:5000/api/rehabilitation-plans', planData, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      console.log('✅ Rehabilitation plan created successfully');
      console.log('Plan ID:', planResponse.data.plan._id);
      console.log('Plan Name:', planResponse.data.plan.planName);
      console.log('Exercises:', planResponse.data.plan.exercises.length);
      
      const planId = planResponse.data.plan._id;
      
      // Get today's exercises
      console.log('\n📅 Fetching today\'s exercises...');
      const todayResponse = await axios.get(`http://localhost:5000/api/rehabilitation-plans/${planId}/today`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      console.log('✅ Today\'s exercises fetched successfully');
      console.log('Exercises for today:', todayResponse.data.exercises.length);
      
      todayResponse.data.exercises.forEach((exercise, index) => {
        console.log(`  ${index + 1}. ${exercise.name} (${exercise.duration} min) - ${exercise.completion.status}`);
      });
      
      console.log('\n🎯 API Endpoints Working:');
      console.log('✅ POST /api/rehabilitation-plans - Create plan');
      console.log('✅ GET /api/rehabilitation-plans/:id/today - Get today\'s exercises');
      console.log('✅ Database integration working');
      console.log('✅ Exercise tracking ready');
      
    } else {
      console.log('No cases found for testing');
    }
    
  } catch (error) {
    console.error('❌ ERROR:');
    console.error('Message:', error.message);
    console.error('Code:', error.code);
    if (error.response) {
      console.error('Status:', error.response.status);
      console.error('Data:', error.response.data);
    } else if (error.request) {
      console.error('Request made but no response received');
    }
  }
}

testRehabilitationPlanAPI();
