const mongoose = require('mongoose');

const rehabilitationPlanSchema = new mongoose.Schema({
  // Case reference
  case: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Case',
    required: true
  },
  
  // Worker reference
  worker: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Clinician who created the plan
  clinician: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Plan details
  planName: {
    type: String,
    required: true,
    default: 'Recovery Plan'
  },
  
  planDescription: {
    type: String,
    default: 'Daily recovery exercises and activities'
  },
  
  // Plan status
  status: {
    type: String,
    enum: ['active', 'paused', 'completed', 'cancelled'],
    default: 'active'
  },
  
  // Plan duration
  startDate: {
    type: Date,
    required: true,
    default: Date.now
  },
  
  endDate: {
    type: Date
  },
  
  // Daily exercises/activities
  exercises: [{
    name: {
      type: String,
      required: true
    },
    description: {
      type: String
    },
    duration: {
      type: Number, // in minutes
      required: true
    },
    instructions: {
      type: String
    },
    category: {
      type: String,
      enum: ['stretching', 'strengthening', 'cardio', 'flexibility', 'balance', 'other'],
      default: 'other'
    },
    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'easy'
    },
    isRequired: {
      type: Boolean,
      default: true
    }
  }],
  
  // Daily completion tracking
  dailyCompletions: [{
    date: {
      type: Date,
      required: true
    },
    exercises: [{
      exerciseId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true
      },
      status: {
        type: String,
        enum: ['completed', 'skipped', 'not_started'],
        default: 'not_started'
      },
      completedAt: {
        type: Date
      },
      skippedReason: {
        type: String,
        enum: ['pain', 'fatigue', 'time_constraint', 'equipment', 'other'],
        default: null
      },
      skippedNotes: {
        type: String
      },
      duration: {
        type: Number // actual duration completed
      }
    }],
    overallStatus: {
      type: String,
      enum: ['completed', 'partial', 'skipped', 'not_started'],
      default: 'not_started'
    },
    completedAt: {
      type: Date
    },
    notes: {
      type: String
    }
  }],
  
  // Progress tracking
  progressStats: {
    totalDays: {
      type: Number,
      default: 0
    },
    completedDays: {
      type: Number,
      default: 0
    },
    skippedDays: {
      type: Number,
      default: 0
    },
    consecutiveCompletedDays: {
      type: Number,
      default: 0
    },
    consecutiveSkippedDays: {
      type: Number,
      default: 0
    },
    lastCompletedDate: {
      type: Date
    },
    lastSkippedDate: {
      type: Date
    }
  },
  
  // Notifications and alerts
  alerts: [{
    type: {
      type: String,
      enum: ['skipped_sessions', 'progress_milestone', 'plan_review_needed'],
      required: true
    },
    message: {
      type: String,
      required: true
    },
    triggeredAt: {
      type: Date,
      default: Date.now
    },
    isRead: {
      type: Boolean,
      default: false
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed
    }
  }],
  
  // Plan settings
  settings: {
    autoGenerateDaily: {
      type: Boolean,
      default: true
    },
    reminderTime: {
      type: String, // HH:MM format
      default: '09:00'
    },
    allowSkipping: {
      type: Boolean,
      default: true
    },
    maxConsecutiveSkips: {
      type: Number,
      default: 2
    },
    progressMilestoneDays: {
      type: Number,
      default: 5
    }
  }
}, {
  timestamps: true
});

// Indexes for better performance
rehabilitationPlanSchema.index({ case: 1, worker: 1 });
rehabilitationPlanSchema.index({ worker: 1, status: 1 });
rehabilitationPlanSchema.index({ 'dailyCompletions.date': 1 });

// Virtual for today's completion status
rehabilitationPlanSchema.virtual('todaysCompletion').get(function() {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  console.log('Getting today\'s completion for date:', today.toISOString());
  
  const todaysCompletion = this.dailyCompletions.find(completion => {
    const completionDate = new Date(completion.date);
    completionDate.setHours(0, 0, 0, 0);
    console.log('Checking completion date:', completionDate.toISOString(), 'matches:', completionDate.getTime() === today.getTime());
    return completionDate.getTime() === today.getTime();
  });
  
  console.log('Found today\'s completion:', todaysCompletion ? 'Yes' : 'No');
  return todaysCompletion;
});

// Method to get today's exercises
rehabilitationPlanSchema.methods.getTodaysExercises = function() {
  console.log('Getting today\'s exercises, total exercises:', this.exercises.length);
  console.log('Today\'s completion:', this.todaysCompletion);
  
  const exercises = this.exercises.map(exercise => {
    const completion = this.todaysCompletion?.exercises.find(e => 
      e.exerciseId.toString() === exercise._id.toString()
    ) || { status: 'not_started' };
    
    console.log(`Exercise ${exercise.name}: status = ${completion.status}`);
    
    return {
      ...exercise.toObject(),
      completion
    };
  });
  
  console.log('Returning exercises:', exercises.length);
  return exercises;
};

// Method to mark exercise as completed
rehabilitationPlanSchema.methods.markExerciseCompleted = function(exerciseId, duration) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  let todaysCompletion = this.dailyCompletions.find(completion => {
    const completionDate = new Date(completion.date);
    completionDate.setHours(0, 0, 0, 0);
    return completionDate.getTime() === today.getTime();
  });
  
  if (!todaysCompletion) {
    todaysCompletion = {
      date: today,
      exercises: [],
      overallStatus: 'not_started'
    };
    this.dailyCompletions.push(todaysCompletion);
  }
  
  const exerciseCompletion = todaysCompletion.exercises.find(e => 
    e.exerciseId.toString() === exerciseId.toString()
  );
  
  if (exerciseCompletion) {
    exerciseCompletion.status = 'completed';
    exerciseCompletion.completedAt = new Date();
    exerciseCompletion.duration = duration;
  } else {
    todaysCompletion.exercises.push({
      exerciseId,
      status: 'completed',
      completedAt: new Date(),
      duration: duration
    });
  }
  
  // Update overall status
  const completedExercises = todaysCompletion.exercises.filter(e => e.status === 'completed').length;
  const totalExercises = this.exercises.length;
  
  console.log(`Exercise completion: ${completedExercises}/${totalExercises} completed`);
  
  if (completedExercises === totalExercises) {
    todaysCompletion.overallStatus = 'completed';
    todaysCompletion.completedAt = new Date();
    console.log('All exercises completed for today!');
  } else if (completedExercises > 0) {
    todaysCompletion.overallStatus = 'partial';
    console.log('Partial completion for today');
  }
  
  console.log('Today\'s overall status:', todaysCompletion.overallStatus);
  
  // Update progress stats
  this.updateProgressStats();
  
  return this.save();
};

// Method to mark exercise as skipped
rehabilitationPlanSchema.methods.markExerciseSkipped = function(exerciseId, reason, notes) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  let todaysCompletion = this.dailyCompletions.find(completion => {
    const completionDate = new Date(completion.date);
    completionDate.setHours(0, 0, 0, 0);
    return completionDate.getTime() === today.getTime();
  });
  
  if (!todaysCompletion) {
    todaysCompletion = {
      date: today,
      exercises: [],
      overallStatus: 'not_started'
    };
    this.dailyCompletions.push(todaysCompletion);
  }
  
  const exerciseCompletion = todaysCompletion.exercises.find(e => 
    e.exerciseId.toString() === exerciseId.toString()
  );
  
  if (exerciseCompletion) {
    exerciseCompletion.status = 'skipped';
    exerciseCompletion.skippedReason = reason;
    exerciseCompletion.skippedNotes = notes;
  } else {
    todaysCompletion.exercises.push({
      exerciseId,
      status: 'skipped',
      skippedReason: reason,
      skippedNotes: notes
    });
  }
  
  // Update progress stats
  this.updateProgressStats();
  
  return this.save();
};

// Method to update progress statistics
rehabilitationPlanSchema.methods.updateProgressStats = function() {
  const completions = this.dailyCompletions.sort((a, b) => new Date(a.date) - new Date(b.date));
  
  console.log('Updating progress stats...');
  console.log('Total daily completions:', completions.length);
  console.log('Completions:', completions.map(c => ({
    date: c.date,
    overallStatus: c.overallStatus,
    exercises: c.exercises.length
  })));
  
  this.progressStats.totalDays = completions.length;
  this.progressStats.completedDays = completions.filter(c => c.overallStatus === 'completed').length;
  this.progressStats.skippedDays = completions.filter(c => c.overallStatus === 'skipped').length;
  
  console.log('Calculated stats:', {
    totalDays: this.progressStats.totalDays,
    completedDays: this.progressStats.completedDays,
    skippedDays: this.progressStats.skippedDays
  });
  
  // Calculate consecutive days - fix the logic
  let consecutiveCompleted = 0;
  let consecutiveSkipped = 0;
  
  // For consecutive completed days, count from the most recent day backwards
  for (let i = completions.length - 1; i >= 0; i--) {
    if (completions[i].overallStatus === 'completed') {
      consecutiveCompleted++;
    } else if (completions[i].overallStatus === 'skipped' || completions[i].overallStatus === 'partial') {
      // Stop counting if we hit a skipped or partial day
      break;
    } else {
      // Stop counting if we hit a not_started day
      break;
    }
  }
  
  // For consecutive skipped days, count from the most recent day backwards
  for (let i = completions.length - 1; i >= 0; i--) {
    if (completions[i].overallStatus === 'skipped') {
      consecutiveSkipped++;
    } else if (completions[i].overallStatus === 'completed' || completions[i].overallStatus === 'partial') {
      // Stop counting if we hit a completed or partial day
      break;
    } else {
      // Stop counting if we hit a not_started day
      break;
    }
  }
  
  this.progressStats.consecutiveCompletedDays = consecutiveCompleted;
  this.progressStats.consecutiveSkippedDays = consecutiveSkipped;
  
  console.log('Consecutive stats:', {
    consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
    consecutiveSkippedDays: this.progressStats.consecutiveSkippedDays
  });
  
  // Update last completed/skipped dates
  const lastCompleted = completions.filter(c => c.overallStatus === 'completed').pop();
  const lastSkipped = completions.filter(c => c.overallStatus === 'skipped').pop();
  
  if (lastCompleted) {
    this.progressStats.lastCompletedDate = lastCompleted.date;
  }
  if (lastSkipped) {
    this.progressStats.lastSkippedDate = lastSkipped.date;
  }
  
  console.log('Final progress stats:', this.progressStats);
};

// Method to get current progress stats (with debugging)
rehabilitationPlanSchema.methods.getProgressStats = function() {
  console.log('Getting progress stats...');
  console.log('Current stats:', this.progressStats);
  console.log('Daily completions count:', this.dailyCompletions.length);
  
  return this.progressStats;
};

// Method to ensure progress stats are properly initialized
rehabilitationPlanSchema.methods.ensureProgressStats = function() {
  if (!this.progressStats) {
    this.progressStats = {
      totalDays: 0,
      completedDays: 0,
      skippedDays: 0,
      consecutiveCompletedDays: 0,
      consecutiveSkippedDays: 0
    };
  }
  
  // Always update stats to ensure they're current
  this.updateProgressStats();
  
  return this.progressStats;
};

// Method to check for alerts
rehabilitationPlanSchema.methods.checkForAlerts = async function() {
  const alerts = [];
  
  console.log('Checking for alerts...');
  console.log('Consecutive completed days:', this.progressStats.consecutiveCompletedDays);
  console.log('Consecutive skipped days:', this.progressStats.consecutiveSkippedDays);
  
  // Check for consecutive skipped sessions
  if (this.progressStats.consecutiveSkippedDays >= (this.settings?.maxConsecutiveSkips || 3)) {
    alerts.push({
      type: 'skipped_sessions',
      message: `Worker has skipped ${this.progressStats.consecutiveSkippedDays} consecutive sessions. Plan review may be needed.`,
      metadata: {
        consecutiveSkippedDays: this.progressStats.consecutiveSkippedDays,
        workerId: this.worker,
        caseId: this.case
      }
    });
  }
  
  // Check for 5-day consecutive completion milestone
  if (this.progressStats.consecutiveCompletedDays === 5) {
    // Check if we already sent a notification for this milestone
    const existingAlert = this.alerts.find(a => 
      a.type === 'five_day_milestone' && 
      a.metadata?.consecutiveCompletedDays === 5
    );
    
    if (!existingAlert) {
      alerts.push({
        type: 'five_day_milestone',
        message: `🎉 Amazing! You've completed all exercises for 5 consecutive days! Your dedication to recovery is inspiring. Keep up the excellent work!`,
        metadata: {
          consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
          milestone: 'five_days',
          workerId: this.worker,
          caseId: this.case
        }
      });
    }
  }
  
  // Check for other progress milestones
  if (this.progressStats.consecutiveCompletedDays === 10) {
    const existingAlert = this.alerts.find(a => 
      a.type === 'ten_day_milestone' && 
      a.metadata?.consecutiveCompletedDays === 10
    );
    
    if (!existingAlert) {
      alerts.push({
        type: 'ten_day_milestone',
        message: `🌟 Outstanding! 10 consecutive days of completed exercises! You're building incredible momentum in your recovery journey.`,
        metadata: {
          consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
          milestone: 'ten_days',
          workerId: this.worker,
          caseId: this.case
        }
      });
    }
  }
  
  if (this.progressStats.consecutiveCompletedDays === 15) {
    const existingAlert = this.alerts.find(a => 
      a.type === 'fifteen_day_milestone' && 
      a.metadata?.consecutiveCompletedDays === 15
    );
    
    if (!existingAlert) {
      alerts.push({
        type: 'fifteen_day_milestone',
        message: `🏆 Phenomenal! 15 consecutive days! You've developed a strong recovery routine. Your commitment is truly remarkable!`,
        metadata: {
          consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
          milestone: 'fifteen_days',
          workerId: this.worker,
          caseId: this.case
        }
      });
    }
  }
  
  if (this.progressStats.consecutiveCompletedDays === 30) {
    const existingAlert = this.alerts.find(a => 
      a.type === 'thirty_day_milestone' && 
      a.metadata?.consecutiveCompletedDays === 30
    );
    
    if (!existingAlert) {
      alerts.push({
        type: 'thirty_day_milestone',
        message: `🎊 Incredible! A full month of consecutive exercise completion! You've transformed your recovery into a powerful habit. Congratulations!`,
        metadata: {
          consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
          milestone: 'thirty_days',
          workerId: this.worker,
          caseId: this.case
        }
      });
    }
  }
  
  // Check for general progress milestone (if different from specific milestones)
  if (this.progressStats.consecutiveCompletedDays >= (this.settings?.progressMilestoneDays || 7) && 
      ![5, 10, 15, 30].includes(this.progressStats.consecutiveCompletedDays)) {
    alerts.push({
      type: 'progress_milestone',
      message: `Great progress! Worker has completed ${this.progressStats.consecutiveCompletedDays} consecutive sessions.`,
      metadata: {
        consecutiveCompletedDays: this.progressStats.consecutiveCompletedDays,
        workerId: this.worker,
        caseId: this.case
      }
    });
  }
  
  // Add new alerts
  if (alerts.length > 0) {
    console.log('Adding alerts:', alerts.length);
    this.alerts.push(...alerts);
    await this.save();
  }
  
  return alerts;
};

// Method to get milestone progress information
rehabilitationPlanSchema.methods.getMilestoneProgress = function() {
  const milestones = [
    { days: 5, name: 'five_days', emoji: '🎉', message: '5-Day Streak!' },
    { days: 10, name: 'ten_days', emoji: '🌟', message: '10-Day Streak!' },
    { days: 15, name: 'fifteen_days', emoji: '🏆', message: '15-Day Streak!' },
    { days: 30, name: 'thirty_days', emoji: '🎊', message: '30-Day Streak!' }
  ];
  
  const currentStreak = this.progressStats.consecutiveCompletedDays;
  
  return milestones.map(milestone => ({
    ...milestone,
    achieved: currentStreak >= milestone.days,
    next: currentStreak < milestone.days && 
          (milestone.days === 5 || currentStreak >= milestones[milestones.indexOf(milestone) - 1]?.days || milestones.indexOf(milestone) === 0),
    progress: Math.min((currentStreak / milestone.days) * 100, 100)
  }));
};

module.exports = mongoose.model('RehabilitationPlan', rehabilitationPlanSchema);
